source/acknowledgements.rst
Signed-off-by: Manuel Groß <mgr@nordkrater.de>
=> Add missing word

source/devicetree-basics.rst
Node name *can* was mentioned twice in the list, removed one (and preserving alphabetical order).
=> Remove duplicated node name recommendation

source/devicetree-basics.rst
This PR is based on my talk with Rob where i2c-mux should be used but it is not listed. 
And there is no standard name for ina226 chip that's why I choose power-monitor.
=> Record i2c-mux and power-monitor names

source/devicetree-basics.rst
We use this on Bare metal Power 8/9 systems to mark devices that
are used by the OPAL firmware rather than being available to the
operating system.
Signed-off-by: Oliver O'Halloran <oohall@gmail.com>
=> Document the reserved status

source/devicetree-basics.rst
LoRa (Long Range) is a wireless communication technology operates in the
Sub-Gigahertz spectrum. LoRa usually implies to the radio which acts as a
transceiver. Hence, add it as a standard node name.
We have these devices in Zephyr which uses devicetree.
Signed-off-by: Manivannan Sadhasivam <manivannan.sadhasivam@linaro.org>
=> Add lora as a standard node name

source/devicetree-basics.rst
We have had drivers for these type of sensors in kernel for some time
already hence add a new node name to the list for completeness.
Signed-off-by: Tomasz Duszynski <tduszyns@gmail.com>
=> Add air-pollution-sensor to the recommended node names

source/devicetree-basics.rst
co2-sensor node name has recently appeared in one of binding files hence
should be documented here as well for completeness.
Signed-off-by: Tomasz Duszynski <tomasz.duszynski@octakon.com>
=> Add co2-sensor to the recommended node names

source/chapter2-devicetree-basics.rst
Require node name w/o unit-address and property names to be unique
if they exist as the same level in the tree.
Signed-off-by: Kumar Gala <kumar.gala@linaro.org>
=> Add addtional constraint on node name and property names.

source/chapter4-device-bindings.rst
This property indicates that nodes which are direct children of this bus
shall use non-posted (i.e. no early return) MMIO mapping modes when
mapping MMIO registers. This is a requirement that can be imposed by the
bus on otherwise generic devices.
Signed-off-by: Hector Martin <marcan@marcan.st>
=> simple-bus: Add nonposted-mmio property

source/chapter2-devicetree-basics.rst
Mostly we use lower case and we try to avoid underscores. Add a note
about this.
I believe this is just writing down the existing conventions. I have not
gone as far as using a character table (as with aliases) or specifying a
maximum length.
(this was reference at https://github.com/zephyrproject-rtos/zephyr/issues/29689#issuecomment-720533574 )
Signed-off-by: Simon Glass <sjg@chromium.org>
=> Add more restrictions on compatible strings

source/chapter2-devicetree-basics.rst
Commit 05a34819e5 ("Add more restrictions on compatible strings")
started to add recommendations on the contents of compatible strings.
Add an additional recommendation that compatibles should start with a
letter. In particular, this matches what dt-schema is doing.
Signed-off-by: Martí Bolívar <marti.bolivar@nordicsemi.no>
=> Add note about the initial character in a compatible

source/chapter3-devicenodes.rst
ACPI-based systems generally provide DMI data allowing userspace software to identify the form-factor of the running system.
Such information can be useful (for example, in order to implement different behavior on a desktop and on a smartphone) but is not readily available on DT-based systems.
This patch proposes adding a new optional property to the root node, allowing a way to specify the system form factor.
The new property is named `chassis-type`, using the same values as systemd's [hostnamed](https://www.freedesktop.org/software/systemd/man/machine-info.html#CHASSIS=).
=> Add new 'chassis-type' root node property

source/chapter2-devicetree-basics.rst
System Power Management Interface Protocol (SPMI) is a MIPI standard
bus used to connect the Power Management Integrated Circuits (PMIC)
to the SoCs. Let's add "spmi" to the list of generic node names.
Signed-off-by: Manivannan Sadhasivam <manivannan.sadhasivam@linaro.org>
=> Add SPMI to the list of generic node names

source/chapter2-devicetree-basics.rst
Similar to the 'dma-coherent' property, some architectures may be coherent
by default with some devices being non-coherent. Add a property for this
case tool.
Signed-off-by: Heiko Stuebner <heiko@sntech.de>
=> Add 'dma-noncoherent' property as a standard property

source/chapter2-devicetree-basics.rst
The current definition is causing people to decide that only 'real' hardware devices should be in the device tree. Rewrite two paragraphs to adjust this.
Signed-off-by: Simon Glass <sjg@chromium.org>
=> Adjust language around what a device is

source/chapter3-devicenodes.rst
Modern CPU implementations overwhelmingly implement frequency scaling, so there is no real notion of "the current" CPU clock frequency anymore.
Make the "clock-frequency" and "timebase-frequency" property of each CPU node optional instead of required, and reword the description of the clock-frequency to only encourage using this property if the CPU speed is fixed.
Signed-off-by: Andre Przywara <andre.przywara@arm.com>
=> cpus node: Make clock-frequency optional

source/chapter2-devicetree-basics.rst
UFS Host Controller (ufshc) is reponsible for managing the interface between host SW stack and UFS device.
In a lot of places, 'ufs' is used as the node name to identify the host controller, but it is wrong since 'ufs' denotes 'UFS device'.
=> Add UFS Host Controller to the list of generic node names

source/chapter2-devicetree-basics.rst
- rename open-pic to open_pic to be syntactically valid
- add a name@addr to open_pic, because dtc otherwise says it cannot be found
resolves #75
=> chapter2: fix example for open_pic

source/chapter3-devicenodes.rst
The 'television' chassis type includes Smart TVs and set-top boxes, or any remote-controlled displays in general.
---
Hi,
I plan to use this chassis type in version 2 of the patches to add [initial device trees for Apple A7-A11 SoC based devices](https://lore.kernel.org/asahi/20240911084353.28888-2-towinchenmi@gmail.com/),
which includes Apple TV.
Nick Chan
=> Add 'television' chassis type

source/chapter3-devicenodes.rst
With the growing interest in the AR/VR/XR devices, it is expected that more and more devices will have the spectacles or eyeglasses-like form factor. Allow documenting such devices by specifying the 'spectacles' chassis-type.
=> Add 'spectacles' chassis type

source/chapter3-devicenodes.rst
All in One PCs are desktop computers with integrated display. The Linux kernel contains device trees for Apple silicon iMacs [0] which are best described by this chassis-type.
The SMBIOS specification [1] specifies "All in One" as `0Dh` in "Table 17 – System Enclosure or Chassis Types" as well.
[0] arch/arm64/boot/dts/apple/t8103-j45[67].dts
[1] https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.8.0.pdf
=> Add "all-in-one" chassis-type
